// <auto-generated />
namespace HMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class identityframeworkrefference : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identityframeworkrefference));
        
        string IMigrationMetadata.Id
        {
            get { return "202209062205011_identityframeworkrefference"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
